### ISSUE TITLE
New name?

### ISSUE THREAD

**Issue by bertob** [sonnyp/Commit#28]
As discussed in the [Circle issue](https://gitlab.gnome.org/Teams/Circle/-/issues/83) my feeling is the current name is not terrible but a bit too generic. Something with a bit more personality would be nicer.

Some ideas to get the ball rolling:
- Savepoint
- Checkpoint
- Commitment
- Snapshot

**Comment by sonnyp** [comment]
What about `Commie ☭` ? :trollface:

I don't understand, why replacing a generic word with an other one that is less descriptive / memorable ?

**Comment by aral** [comment]
Commit is a perfectly fine name.

**Comment by Tachi107** [comment]
> I don't understand, why replacing a generic word [...]?

For example, to help downstream packaging. Commit is an appropriate name for the app, but wouldn't be for a package name, since distros don't follow Flatpack's "reverse domain name" convention and `commit` as a package name would too generic: "commit" what?

As an example, Debian does not currently provide any package named `commit`, but they discourage the use of generic terms because they would pollute the namespace (and there is just a single one, no `tld.org.app`), and getting a package named `commit` in the archive would be somewhat hard.

I would suggest to not necessairly change the app's name, but at least provide an alternative one that packagers could use to name the package; @sonnyp, would something like `sonnyp-commit` be appropriate for a package name in your opinion?

**Comment by sonnyp** [comment]
My sentence was

> why replacing a generic word with an other one

It doesnt matter what I name commit, the problem you raise remains the same. At least "commit" is available...

It's only gonna get worse with time. That's why reverse DNS naming exists.

Anyway, distributions have diffetent policies and it doesn't make sense for me to say what the package should be named.

I prefer "commit" but if that doesn't work, I think it's something for distributions to figure out; if they don't want to use reverse DNS or a 1:1 with it like re-sonny-commit 

What distribution would you package it for? Im sure you this isn't the first time this is raised.

Closing this issue as commit is not gonna change name.

**Comment by Tachi107** [comment]
> It's only gonna get worse with time. That's why reverse DNS naming exists.

I agree, having only a global namespace sucks :/

> Anyway, distributions have different policies and it doesn't make sense for me to say what the package should be named.
> 
> I prefer "commit" but if that doesn't work and they don't want to use reverse DNS or a 1:1 with it like re-sonny-commit I think it's something for distributions to figure out;

There's no "they", It's something upstream and downstream can talk about :)
I could submit a package named re-sonny-commit without issues; if you're happy with it, I'm happy too. It is a bit less clean than a short name but I believe it is not an issue (graphical stores don't show package names and terminal users can handle "strange" names)

> What distribution would you package it for? I'm sure this isn't the first time this is raised.

Debian (and derivatives like Ubuntu). I searched in the issue tracker but I couldn't find anything related to packaging (apart from the AUR package)

**Comment by sonnyp** [comment]
There is definitely "they" for me - even if it's "we" for you :smile: 

> Debian (and derivatives like Ubuntu). I searched in the issue tracker but I couldn't find anything related to packaging (apart from the AUR package)

I meant - doesn't Debian/Ubuntu already have policies or guidelines for this ?

The app id (reverse DNS) can be changed in flatpak repositories / flathub I gueess it might be a problem for apt package names.

I think an other good option  is `commit-message-editor`

**Comment by Tachi107** [comment]
> I meant - doesn't Debian/Ubuntu already have policies or guidelines for this ?

They have policies regarding technical things like non-allowed characters and restrictions on too generic names, but as far as I know (I'm relatively new to packaging) they don't have guidelines regarding the actual package name

> The app id (reverse DNS) can be changed in flatpak repositories / flathub I gueess it might be a problem for apt package names.

Yep, changing a package name is a bit of an issue :/

> I think an other good option is `commit-editor` or `commit-message-editor` (preferred)

Ok, `commit-message-editor` seems a good choice :)

I never packaged JS stuff (and never used it for anything serious), but I'll let you know when the package will be ready!

**Comment by sonnyp** [comment]
> I never packaged JS stuff (and never used it for anything serious)

Should be very straightforward, it's a standard meson / GNOME app setup.

Look into how other GNOME JavaScript apps are packaged. https://gitlab.gnome.org/GNOME/gjs/-/blob/master/doc/Home.md

> but I'll let you know when the package will be ready!

Cool, appreciate
