### ISSUE TITLE
enhancement: allow configuration of font and text size

### ISSUE THREAD

**Issue by travisfw** [sonnyp/Commit#79]
I like the simple, clean interface. Also I'd like ctrl-+ to increase the font size like it does in some other apps, or at least, have a menu item for it.

**Comment by sonnyp** [comment]
What for?

**Comment by travisfw** [comment]
Uh. Comfort? Less squinting. Faster reading. Why not? The window is a small fraction of my screen. Its usage is brief. Why not be large and center, instead of small and off to the left?

**Comment by sonnyp** [comment]
> Comfort? Less squinting. Faster reading

Why isn't your default font size comfortable? 

If you use GNOME there is an accessibility feature "Large Text".

> Why not?

Because options aren't always good, and I'm not going to implement something without a clear use case.

> Why not be large and center,

Commit doesn't decide where it's placed on the screen, your window manager does. https://github.com/sonnyp/Commit#open-commit-in-the-center-of-the-screen

I'm sure your WM has a shortcut to make windows bigger. See also https://github.com/sonnyp/Commit/issues/58

**Comment by travisfw** [comment]
If your philosophy is to use system settings, that would be great. I tried changing "document text" font in the Gnome Tweaks tool, but it didn't make a difference. Would you support setting font size that way?

**Comment by sonnyp** [comment]
Works for me. 

What's your OS/DE and how did you install Commit?

**Comment by travisfw** [comment]
I'm on Fedora 36, and iirc I discovered Commit through the Software gui application, and installed the flatpak.

**Comment by sonnyp** [comment]
Also use Fedora 36

Try installing as user

```
flatpak remove re.sonny.Commit
flatak install --user re.sonny.Commit
```

**Comment by travisfw** [comment]
I'm sure I'm making a rookie mistake, but what am I missing here:
```
$ flatpak install --user re.sonny.Commit
Looking for matches…
error: No remote refs found similar to ‘re.sonny.Commit’
```
I can actually see Commit in the Software app, but if I install from there it won't be --user.
