### ISSUE TITLE
Unable to edit commit text after it has been copy-pasted

### ISSUE THREAD

**Issue by umbe-dev** [sonnyp/Commit#87]
## How to reproduce:

- Open the commit editor
- Copy some text from somewhere else and paste it on the editor
- Try to edit the text you just pasted

OS: Fedora 36

**Comment by fkinoshita** [comment]
I'm unable to reproduce this, does it still happen for you?

**Comment by sonnyp** [comment]
I also can't reproduce.

**Comment by semkowicz** [comment]
I also faced the same issue. It looks like the problem occurs after you copy part of the text already present in the editor. For example, when invoking `git commit`, there will be a commented text at the bottom of the file. If you copy part of this message, it is no longer possible to erase the pasted text.

Below is the video of the problem happening. After pasting the word "ignored," it is not possible to erase it or type something after it. The only way to work around the problem is to use CTRL + Z.

https://github.com/user-attachments/assets/d9bfde8f-65fe-434f-aaca-b34910ec40e3
